# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Bird

on:
  # issues:
  #   types: [ "labeled" ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      go_version: "1.23.4"
      target_name: "bird"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      id: setup-go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.go_version }}

    - name: Display Go version
      run: go version

    - name: Build
      run: go build -o $target_name .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.target_name }}
        path: ${{ env.target_name }}
